<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button></ion-back-button>
        </ion-buttons>
        <ion-title>Patent List</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content class="ion-padding">
      <ion-searchbar
        show-clear-button="always"
        :clear-icon="trashBin"
        placeholder="input patent name"
      ></ion-searchbar>

      <ion-grid class="grid-scroll">
        <ion-row class="row-head">
          <ion-col size="2">序号</ion-col>
          <ion-col size="5">名称</ion-col>
          <ion-col size="4">类型</ion-col>
          <ion-col size="6">申请号/登记号</ion-col>
          <ion-col size="4">参与人</ion-col>
          <ion-col size="4">所属部门</ion-col>
        </ion-row>

        <ion-row
          class="row-scroll"
          v-for="(it, index) in items"
          :key="it.dbid"
          @click="showDetail(it)"
        >
          <ion-col size="2">{{ index }}</ion-col>
          <ion-col size="5">{{ it.name }}</ion-col>
          <ion-col size="4">{{ it.type.name }}</ion-col>
          <ion-col size="6">{{ it.number }}</ion-col>
          <ion-col size="4">
            <i v-for="p in it.persons" :key="p.dbid">{{ p.name }},</i>
          </ion-col>
          <ion-col size="4">{{ it.department.name }}</ion-col>
        </ion-row>
      </ion-grid>
    </ion-content>
  </ion-page>
</template>
    
    <script>
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonButtons,
  IonBackButton,
  IonTitle,
  IonContent,
  IonList,
  IonItem,
  IonSearchbar,
  IonGrid,
  IonRow,
  IonCol,
} from "@ionic/vue";
import { trashBin } from "ionicons/icons";
export default {
  data() {
    return {
      icons: { trashBin },
      items: [
        {
          dbid: "Fem04pOAAAA",
          name: "一种云上花盆",
          typeId: "Df_FW4NAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPbwYAY",
          number: "202222779008.5",
          appDate: "2022-10-21",
          agencyId: "Ej7i_XYAAAA",
          statusId: "checked",
          submitDate: "2022-10-24",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-10-24",
          persons: [
            {
              dbid: "FfzVOnmAAAA",
              intelId: "Fem04pOAAAA",
              userId: "Db2MP-8GQIg",
              name: "郑伟",
              personType: "js",
              order: 1,
              appNo: "20090046",
              deptName: "建筑与城市规划学院",
              contactsType: "fzr",
              contactsPhone: "15025136865",
              contactsEmail: "57280234@qq.com",
              deptId: "DZb3OPbwYAY",
            },
            {
              dbid: "FfzVOnmAAAE",
              intelId: "Fem04pOAAAA",
              name: "赵洁",
              personType: "yjs",
              order: 2,
              appNo: "20212138038",
              deptName: "建筑与城市规划学院",
              contactsType: "lxr",
              contactsPhone: "15025737163",
              contactsEmail: "310374853@qq.com",
              deptId: "DZb3OPbwYAY",
            },
            {
              dbid: "FfzVOnnAAAA",
              intelId: "Fem04pOAAAA",
              userId: "Db2MP-3GQAk",
              name: "徐晓丹",
              personType: "js",
              order: 3,
              appNo: "20090148",
              deptName: "建筑与城市规划学院",
              contactsType: "ptr",
              deptId: "DZb3OPbwYAY",
            },
          ],
          department: {
            dbid: "DZb3OPbwYAY",
            name: "大龙村",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FW4NAAAA",
            name: "实用新型专利",
          },
        },
        {
          dbid: "FdALfT2AAAA",
          name: "一种带入出水检测的可调功率发射电路",
          typeId: "Df_FW4NAAAA",
          affiliation: "gn",
          departmentId: "DZEapgUyQAQ",
          number: "202222737580.5",
          appDate: "2022-10-18",
          agencyId: "Ej7i_XYAAAA",
          source: "工程研究",
          statusId: "checked",
          submitDate: "2022-10-20",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-10-20",
          persons: [
            {
              dbid: "FfflnX_AAAA",
              intelId: "FdALfT2AAAA",
              name: "付国航",
              personType: "yjs",
              order: 1,
              appNo: "20212204062",
              deptName: "信息工程与自动化学院",
              contactsType: "lxr",
              contactsPhone: "18087143660",
              contactsEmail: "543140979@qq.com",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FfflnX_AAAE",
              intelId: "FdALfT2AAAA",
              userId: "Db2MP-uGQKk",
              name: "金建辉",
              personType: "js",
              order: 2,
              appNo: "12309127",
              deptName: "信息工程与自动化学院",
              contactsType: "fzr",
              contactsPhone: "13085372581",
              contactsEmail: "jjhkm163@163.com",
              deptId: "DZEapgUyQAQ",
            },
          ],
          department: {
            dbid: "DZEapgUyQAQ",
            name: "麒麟区政府",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FW4NAAAA",
            name: "实用新型专利",
          },
        },
        {
          dbid: "FapzrfMAAAA",
          name: "一种简易便携式测流系统装置",
          typeId: "Df_FW4NAAAA",
          affiliation: "gn",
          departmentId: "DZEapgUyQAQ",
          number: "202222469722.4",
          appDate: "2022-09-19",
          agencyId: "Ej7i_XYAAAA",
          source: "横向科研",
          statusId: "checked",
          submitDate: "2022-09-20",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-09-20",
          persons: [
            {
              dbid: "FdESOPKAAAA",
              intelId: "FapzrfMAAAA",
              name: "刘沅林",
              personType: "yjs",
              order: 1,
              appNo: "2022204013",
              deptName: "信息工程与自动化学院",
              contactsType: "lxr",
              contactsPhone: "13038642886",
              contactsEmail: "liuyuanlins@outlook.com",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FdESOPKAAAE",
              intelId: "FapzrfMAAAA",
              userId: "Db2MP-uGQKk",
              name: "金建辉",
              personType: "js",
              order: 2,
              appNo: "12309127",
              deptName: "信息工程与自动化学院",
              contactsType: "fzr",
              contactsPhone: "13085372581",
              contactsEmail: "jjhkm163@163.com",
              deptId: "DZEapgUyQAQ",
            },
          ],
          department: {
            dbid: "DZEapgUyQAQ",
            name: "麒麟区政府",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FW4NAAAA",
            name: "实用新型专利",
          },
        },
        {
          dbid: "FYj1w4TAAAA",
          name: "一种小分子丝素蛋白基水凝胶及其制备方法和应用",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "D5THRx1AAAA",
          number: "202211098853.4",
          appDate: "2022-09-09",
          agencyId: "Ej7i_XYAAAA",
          statusId: "checked",
          submitDate: "2022-09-13",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-09-13",
          persons: [
            {
              dbid: "FchXGpgAAAA",
              intelId: "FYj1w4TAAAA",
              userId: "Db2MP-5GQH8",
              name: "牛昱宇",
              personType: "js",
              order: 1,
              appNo: "20140093",
              deptName: "生命科学与技术学院",
              contactsType: "fzr",
              contactsPhone: "13769118349",
              contactsEmail: "niuyy@lpbr.cn",
              deptId: "DZb3OPawYAQ",
            },
            {
              dbid: "FchXGpgAAAE",
              intelId: "FYj1w4TAAAA",
              userId: "EpQs1fAAAAA",
              name: "张磊",
              personType: "js",
              order: 2,
              appNo: "20200128",
              deptName: "灵长类转化医学研究院",
              contactsType: "lxr",
              contactsPhone: "18287177058",
              contactsEmail: "zhangl@lpbr.cn",
              deptId: "D5THRx1AAAA",
            },
            {
              dbid: "FchXGpgAAAI",
              intelId: "FYj1w4TAAAA",
              name: "吴俊模",
              personType: "yjs",
              order: 3,
              appNo: "20201118002",
              deptName: "灵长类转化医学研究院",
              contactsType: "ptr",
              deptId: "D5THRx1AAAA",
            },
          ],
          department: {
            dbid: "D5THRx1AAAA",
            name: "省政府政策研究室",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FYfwO3XAAAA",
          name: "一种体外培养老龄成纤维细胞的培养体系及培养方法和应用",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "D5THRx1AAAA",
          number: "202211092124.8",
          appDate: "2022-09-08",
          agencyId: "Ej7i_XYAAAA",
          statusId: "checked",
          submitDate: "2022-09-08",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-09-08",
          persons: [
            {
              dbid: "FcHTjX-AAAA",
              intelId: "FYfwO3XAAAA",
              userId: "Db2MP-5GQH8",
              name: "牛昱宇",
              personType: "js",
              order: 1,
              appNo: "20140093",
              deptName: "生命科学与技术学院",
              contactsType: "fzr",
              contactsPhone: "13769118349",
              contactsEmail: "niuyy@lpbr.cn",
              deptId: "DZb3OPawYAQ",
            },
            {
              dbid: "FcHTjX-AAAE",
              intelId: "FYfwO3XAAAA",
              name: "吴俊模",
              personType: "yjs",
              order: 2,
              appNo: "20201118002",
              deptName: "灵长类转化医学研究院",
              contactsType: "lxr",
              contactsPhone: "17787419989",
              contactsEmail: "wqunycd@163.com",
              deptId: "D5THRx1AAAA",
            },
            {
              dbid: "FcHTjX-AAAI",
              intelId: "FYfwO3XAAAA",
              userId: "EpQs1fAAAAA",
              name: "张磊",
              personType: "js",
              order: 3,
              appNo: "20200128",
              deptName: "灵长类转化医学研究院",
              contactsType: "ptr",
              deptId: "D5THRx1AAAA",
            },
          ],
          department: {
            dbid: "D5THRx1AAAA",
            name: "省政府政策研究室",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "Fcq8DvFAAAA",
          name: "一种地下管网管道连接密封装置及方法 ",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPXwYAA",
          number: "202111011883.2",
          appDate: "2022-08-31",
          authoredDate: "2022-05-06",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-09-19",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-09-15",
          history: [
            {
              dbid: "FdAAWzdAAAA",
              inteappId: "Fcq8DvFAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-09-19T15:02:44.638Z",
            },
            {
              dbid: "Fc7UalYAAAA",
              inteappId: "Fcq8DvFAAAA",
              statusId: "await",
              userId: "Db2MP-VGQDI",
              userName: "吴张永",
              timestamp: "2022-09-18T17:12:16.921Z",
            },
            {
              dbid: "FcvmX8rAAAA",
              inteappId: "Fcq8DvFAAAA",
              statusId: "returned",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-09-16T10:35:18.124Z",
              note: "请以证书为依据填写所有参与人信息（含学生和校外人员）！",
            },
            {
              dbid: "FcrYAVmAAAA",
              inteappId: "Fcq8DvFAAAA",
              statusId: "await",
              userId: "Db2MP-VGQDI",
              userName: "吴张永",
              timestamp: "2022-09-15T14:54:02.535Z",
            },
            {
              dbid: "Fcq8DvGAAAI",
              inteappId: "Fcq8DvFAAAA",
              statusId: "draft",
              userId: "Db2MP-VGQDI",
              userName: "吴张永",
              timestamp: "2022-09-15T12:51:56.423Z",
            },
          ],
          persons: [
            {
              dbid: "Fc7UNhAAAAA",
              intelId: "Fcq8DvFAAAA",
              userId: "Db2MP-VGQDI",
              name: "吴张永",
              personType: "js",
              order: 1,
              appNo: "11303048",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7UNhAAAAE",
              intelId: "Fcq8DvFAAAA",
              name: "王东圣",
              personType: "yjs",
              order: 2,
              appNo: "20202103036",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7UNhAAAAI",
              intelId: "Fcq8DvFAAAA",
              name: "蒋佳骏",
              personType: "yjs",
              order: 3,
              appNo: "20203103003",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7UNhBAAAM",
              intelId: "Fcq8DvFAAAA",
              name: "卞光明",
              personType: "xw",
              order: 4,
            },
            {
              dbid: "Fc7UNhBAAAQ",
              intelId: "Fcq8DvFAAAA",
              name: "马自刚",
              personType: "xw",
              order: 5,
            },
            {
              dbid: "Fc7UNhBAAAU",
              intelId: "Fcq8DvFAAAA",
              name: "代龙",
              personType: "xw",
              order: 6,
            },
            {
              dbid: "Fc7UNhBAAAY",
              intelId: "Fcq8DvFAAAA",
              name: "刀正仙",
              personType: "xw",
              order: 7,
            },
            {
              dbid: "Fc7UNhAAAAM",
              intelId: "Fcq8DvFAAAA",
              userId: "Db2MP_BGQBk",
              name: "张晓龙",
              personType: "js",
              order: 8,
              appNo: "20030007",
              deptName: "城市学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBk",
            },
            {
              dbid: "Fc7UNhBAAAA",
              intelId: "Fcq8DvFAAAA",
              userId: "Db2MP-WGQFY",
              name: "蔡晓明",
              personType: "js",
              order: 9,
              appNo: "20060039",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7UNhBAAAE",
              intelId: "Fcq8DvFAAAA",
              userId: "Db2MP-VGQEk",
              name: "魏镜弢",
              personType: "js",
              order: 10,
              appNo: "11303058",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7UNhBAAAI",
              intelId: "Fcq8DvFAAAA",
              userId: "Db2MP-WGQDk",
              name: "王庭有",
              personType: "js",
              order: 11,
              appNo: "11303151",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
          ],
          department: {
            dbid: "DZb3OPXwYAA",
            name: "云南省教育厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "Fgdh9jOAAAA",
          name: "一种可反向卡固的炮孔填塞器",
          typeId: "Df_FW4NAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPZwYBE",
          number: "202222161586.2",
          appDate: "2022-08-17",
          authoredDate: "2022-11-01",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-11-02",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-11-01",
          history: [
            {
              dbid: "Fghyi9wAAAA",
              inteappId: "Fgdh9jOAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-11-02T11:16:35.249Z",
            },
            {
              dbid: "FgdsZDXAAAA",
              inteappId: "Fgdh9jOAAAA",
              statusId: "await",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:11:12.920Z",
            },
            {
              dbid: "Fgdh9jQAAAA",
              inteappId: "Fgdh9jOAAAA",
              statusId: "draft",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T15:25:38.833Z",
            },
          ],
          persons: [
            {
              dbid: "Fgdh9jOAAAE",
              intelId: "Fgdh9jOAAAA",
              userId: "Dc0rHt5hsAI",
              name: "王建国",
              personType: "js",
              order: 1,
              appNo: "20200096",
              deptName: "国土资源工程学院",
              contactsType: "lxr",
              contactsPhone: "13759587370",
              contactsEmail: "wangjg0831@163.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdh9jPAAAA",
              intelId: "Fgdh9jOAAAA",
              name: "陶家龙",
              personType: "yjs",
              order: 2,
              appNo: "20212201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdh9jPAAAE",
              intelId: "Fgdh9jOAAAA",
              name: "马军",
              personType: "yjs",
              order: 3,
              appNo: "20181101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdh9jPAAAI",
              intelId: "Fgdh9jOAAAA",
              userId: "Db2MP_CGQEg",
              name: "李祥龙",
              personType: "js",
              order: 4,
              appNo: "20100024",
              deptName: "国土资源工程学院",
              contactsType: "lxr",
              contactsPhone: "13808731158",
              contactsEmail: "7988982@qq.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdh9jPAAAM",
              intelId: "Fgdh9jOAAAA",
              userId: "Db2MP_BGQJA",
              name: "张智宇",
              personType: "js",
              order: 5,
              appNo: "11301052",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
          ],
          department: {
            dbid: "DZb3OPZwYBE",
            name: "云南省财政厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FW4NAAAA",
            name: "实用新型专利",
          },
        },
        {
          dbid: "Fgdq3acAAAA",
          name: "一种掏槽爆破精确钻孔定位试验装置",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPZwYBE",
          number: "202210977858.8",
          appDate: "2022-08-16",
          authoredDate: "2022-11-01",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-11-02",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-11-01",
          history: [
            {
              dbid: "FghxGM8AAAA",
              inteappId: "Fgdq3acAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-11-02T11:10:15.293Z",
            },
            {
              dbid: "FgdsXxPAAAA",
              inteappId: "Fgdq3acAAAA",
              statusId: "await",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:11:07.664Z",
            },
            {
              dbid: "Fgdq3aeAAAA",
              inteappId: "Fgdq3acAAAA",
              statusId: "draft",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:04:32.991Z",
            },
          ],
          persons: [
            {
              dbid: "Fgdq3adAAAA",
              intelId: "Fgdq3acAAAA",
              userId: "Dc0rHt5hsAI",
              name: "王建国",
              personType: "js",
              order: 1,
              appNo: "20200096",
              deptName: "国土资源工程学院",
              contactsType: "fzr",
              contactsPhone: "13759587370",
              contactsEmail: "wangjg0831@163.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAE",
              intelId: "Fgdq3acAAAA",
              userId: "Db2MP_CGQEg",
              name: "李祥龙",
              personType: "js",
              order: 2,
              appNo: "20100024",
              deptName: "国土资源工程学院",
              contactsType: "fzr",
              contactsPhone: "13808731158",
              contactsEmail: "7988982@qq.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAI",
              intelId: "Fgdq3acAAAA",
              userId: "Db2MP_BGQJA",
              name: "张智宇",
              personType: "js",
              order: 3,
              appNo: "11301052",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAM",
              intelId: "Fgdq3acAAAA",
              userId: "Db2MP-0GQIw",
              name: "黄永辉",
              personType: "js",
              order: 4,
              appNo: "20130151",
              deptName: "电力工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYAI",
            },
            {
              dbid: "Fgdq3adAAAQ",
              intelId: "Fgdq3acAAAA",
              name: "关思",
              personType: "yjs",
              order: 5,
              appNo: "20221201005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAU",
              intelId: "Fgdq3acAAAA",
              name: "马军",
              personType: "yjs",
              order: 6,
              appNo: "20181101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAY",
              intelId: "Fgdq3acAAAA",
              name: "胡涛",
              personType: "yjs",
              order: 7,
              appNo: "20221101015",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAc",
              intelId: "Fgdq3acAAAA",
              name: "张小华",
              personType: "yjs",
              order: 8,
              appNo: "20201201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAg",
              intelId: "Fgdq3acAAAA",
              name: "陶子豪",
              personType: "yjs",
              order: 9,
              appNo: "20201101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAk",
              intelId: "Fgdq3acAAAA",
              name: "左庭",
              personType: "yjs",
              order: 10,
              appNo: "20213101005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAo",
              intelId: "Fgdq3acAAAA",
              name: "赵泽虎",
              personType: "yjs",
              order: 11,
              appNo: "20221101025",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAs",
              intelId: "Fgdq3acAAAA",
              name: "雷露刚",
              personType: "yjs",
              order: 12,
              appNo: "20212101095",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdq3adAAAw",
              intelId: "Fgdq3acAAAA",
              name: "陶家龙",
              personType: "yjs",
              order: 13,
              appNo: "20212201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
          ],
          department: {
            dbid: "DZb3OPZwYBE",
            name: "云南省财政厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "Fgdoz33AAAA",
          name: "一种用于预裂爆破模型试验的检测设备及方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPZwYBE",
          number: "202210977898.2",
          appDate: "2022-08-16",
          authoredDate: "2022-11-01",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-11-02",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-11-01",
          history: [
            {
              dbid: "FghxxCyAAAA",
              inteappId: "Fgdoz33AAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-11-02T11:13:10.771Z",
            },
            {
              dbid: "FgdsYN3AAAA",
              inteappId: "Fgdoz33AAAA",
              statusId: "await",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:11:09.496Z",
            },
            {
              dbid: "Fgdoz35AAAA",
              inteappId: "Fgdoz33AAAA",
              statusId: "draft",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T15:55:34.202Z",
            },
          ],
          persons: [
            {
              dbid: "Fgdoz34AAAA",
              intelId: "Fgdoz33AAAA",
              userId: "Dc0rHt5hsAI",
              name: "王建国",
              personType: "js",
              order: 1,
              appNo: "20200096",
              deptName: "国土资源工程学院",
              contactsType: "fzr",
              contactsPhone: "13759587370",
              contactsEmail: "wangjg0831@163.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAE",
              intelId: "Fgdoz33AAAA",
              name: "关思",
              personType: "yjs",
              order: 2,
              appNo: "20221201005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAI",
              intelId: "Fgdoz33AAAA",
              name: "马军",
              personType: "yjs",
              order: 3,
              appNo: "20181101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAM",
              intelId: "Fgdoz33AAAA",
              name: "张小华",
              personType: "yjs",
              order: 4,
              appNo: "20201201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAQ",
              intelId: "Fgdoz33AAAA",
              name: "陶子豪",
              personType: "yjs",
              order: 5,
              appNo: "20201101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAU",
              intelId: "Fgdoz33AAAA",
              name: "左庭",
              personType: "yjs",
              order: 6,
              appNo: "20213101005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAY",
              intelId: "Fgdoz33AAAA",
              name: "赵泽虎",
              personType: "yjs",
              order: 7,
              appNo: "20201101025",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAc",
              intelId: "Fgdoz33AAAA",
              name: "雷露刚",
              personType: "yjs",
              order: 8,
              appNo: "20212101095",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAg",
              intelId: "Fgdoz33AAAA",
              name: "陶家龙",
              personType: "yjs",
              order: 9,
              appNo: "20212201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAk",
              intelId: "Fgdoz33AAAA",
              userId: "Db2MP_CGQEg",
              name: "李祥龙",
              personType: "js",
              order: 10,
              appNo: "20100024",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAo",
              intelId: "Fgdoz33AAAA",
              userId: "Db2MP_BGQJA",
              name: "张智宇",
              personType: "js",
              order: 11,
              appNo: "11301052",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "Fgdoz34AAAs",
              intelId: "Fgdoz33AAAA",
              userId: "Db2MP-0GQIw",
              name: "黄永辉",
              personType: "js",
              order: 12,
              appNo: "20130151",
              deptName: "电力工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYAI",
            },
            {
              dbid: "Fgdoz34AAAw",
              intelId: "Fgdoz33AAAA",
              userId: "Db2MP_EGQG4",
              name: "李洪超",
              personType: "js",
              order: 13,
              appNo: "20160032",
              deptName: "城市学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBk",
            },
            {
              dbid: "Fgdoz34AAA0",
              intelId: "Fgdoz33AAAA",
              userId: "FDp5xT5AAAA",
              name: "侯得峰",
              personType: "js",
              order: 14,
              appNo: "20210199",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
          ],
          department: {
            dbid: "DZb3OPZwYBE",
            name: "云南省财政厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FgdkrPLAAAA",
          name: "一种用于预裂爆破模型试验爆炸应力测试的装置及方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPZwYBE",
          number: "202210977894.4",
          appDate: "2022-08-16",
          authoredDate: "2022-11-01",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-11-02",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-11-01",
          history: [
            {
              dbid: "FghyKAbAAAA",
              inteappId: "FgdkrPLAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-11-02T11:14:53.020Z",
            },
            {
              dbid: "FgdsYpgAAAA",
              inteappId: "FgdkrPLAAAA",
              statusId: "await",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:11:11.265Z",
            },
            {
              dbid: "FgdkrPMAAAo",
              inteappId: "FgdkrPLAAAA",
              statusId: "draft",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T15:37:30.253Z",
            },
          ],
          persons: [
            {
              dbid: "FgdkrPLAAAE",
              intelId: "FgdkrPLAAAA",
              userId: "Dc0rHt5hsAI",
              name: "王建国",
              personType: "js",
              order: 1,
              appNo: "20200096",
              deptName: "国土资源工程学院",
              contactsType: "lxr",
              contactsPhone: "13759587370",
              contactsEmail: "wangjg0831@163.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPLAAAI",
              intelId: "FgdkrPLAAAA",
              name: "雷露刚",
              personType: "yjs",
              order: 2,
              appNo: "20212101095",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPLAAAM",
              intelId: "FgdkrPLAAAA",
              userId: "Db2MP_CGQEg",
              name: "李祥龙",
              personType: "js",
              order: 3,
              appNo: "20100024",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPLAAAQ",
              intelId: "FgdkrPLAAAA",
              name: "张小华",
              personType: "yjs",
              order: 4,
              appNo: "20201201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPLAAAU",
              intelId: "FgdkrPLAAAA",
              name: "马军",
              personType: "yjs",
              order: 5,
              appNo: "20181101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAA",
              intelId: "FgdkrPLAAAA",
              name: "关思",
              personType: "yjs",
              order: 6,
              appNo: "20221201005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAE",
              intelId: "FgdkrPLAAAA",
              userId: "Db2MP_BGQJA",
              name: "张智宇",
              personType: "js",
              order: 7,
              appNo: "11301052",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAI",
              intelId: "FgdkrPLAAAA",
              userId: "Db2MP-0GQIw",
              name: "黄永辉",
              personType: "js",
              order: 8,
              appNo: "20130151",
              deptName: "电力工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYAI",
            },
            {
              dbid: "FgdkrPMAAAM",
              intelId: "FgdkrPLAAAA",
              userId: "Db2MP_EGQG4",
              name: "李洪超",
              personType: "js",
              order: 9,
              appNo: "20160032",
              deptName: "城市学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBk",
            },
            {
              dbid: "FgdkrPMAAAQ",
              intelId: "FgdkrPLAAAA",
              userId: "FDp5xT5AAAA",
              name: "侯得峰",
              personType: "js",
              order: 10,
              appNo: "20210199",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAU",
              intelId: "FgdkrPLAAAA",
              name: "陶家龙",
              personType: "yjs",
              order: 11,
              appNo: "20212201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAY",
              intelId: "FgdkrPLAAAA",
              name: "陶子豪",
              personType: "yjs",
              order: 12,
              appNo: "20201101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAc",
              intelId: "FgdkrPLAAAA",
              name: "左庭",
              personType: "yjs",
              order: 13,
              appNo: "20213101005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdkrPMAAAg",
              intelId: "FgdkrPLAAAA",
              name: "赵泽虎",
              personType: "yjs",
              order: 14,
              appNo: "20221101025",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
          ],
          department: {
            dbid: "DZb3OPZwYBE",
            name: "云南省财政厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FgKTe5pAAAA",
          name: "一种升降式电机张紧平台",
          typeId: "Df_FW4NAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPawYBk",
          number: "202222127251.9",
          appDate: "2022-08-13",
          authoredDate: "2022-10-28",
          agencyId: "DmO7XtuAAAA",
          source: "项目",
          statusId: "checked",
          submitDate: "2022-10-31",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-10-28",
          history: [
            {
              dbid: "FgYgaynAAAA",
              inteappId: "FgKTe5pAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-10-31T16:00:48.232Z",
            },
            {
              dbid: "FgXeUDuAAAA",
              inteappId: "FgKTe5pAAAA",
              statusId: "await",
              userId: "Db2MP_EGQCM",
              userName: "李飞",
              timestamp: "2022-10-31T11:11:59.151Z",
            },
            {
              dbid: "FgXY-IgAAAA",
              inteappId: "FgKTe5pAAAA",
              statusId: "returned",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-10-31T10:48:38.625Z",
              note: "请以证书为依据填写所有参与人信息（含学生和校外人员）！",
            },
            {
              dbid: "FgKTiaAAAAA",
              inteappId: "FgKTe5pAAAA",
              statusId: "await",
              userId: "Db2MP_EGQCM",
              userName: "李飞",
              timestamp: "2022-10-28T21:49:50.529Z",
            },
            {
              dbid: "FgKTe5rAAAA",
              inteappId: "FgKTe5pAAAA",
              statusId: "draft",
              userId: "Db2MP_EGQCM",
              userName: "李飞",
              timestamp: "2022-10-28T21:49:36.172Z",
            },
          ],
          persons: [
            {
              dbid: "FgXeIkcAAAA",
              intelId: "FgKTe5pAAAA",
              userId: "Db2MP_EGQCM",
              name: "李飞",
              personType: "js",
              order: 1,
              appNo: "20130070",
              deptName: "城市学院",
              contactsType: "fzr",
              contactsPhone: "13759108032",
              contactsEmail: "233232417@qq.com",
              deptId: "DZb3OPawYBk",
            },
            {
              dbid: "FgXeIkcAAAE",
              intelId: "FgKTe5pAAAA",
              name: "蔡云秀",
              personType: "xw",
              order: 2,
            },
            {
              dbid: "FgXeIkcAAAI",
              intelId: "FgKTe5pAAAA",
              name: "何敏",
              personType: "bks",
              order: 3,
              appNo: "2020128509144",
              deptName: "城市学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBk",
            },
            {
              dbid: "FgXeIkcAAAM",
              intelId: "FgKTe5pAAAA",
              name: "童芸",
              personType: "bks",
              order: 4,
              appNo: "2020128526159",
              deptName: "城市学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBk",
            },
          ],
          department: {
            dbid: "DZb3OPawYBk",
            name: "城市学院",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FW4NAAAA",
            name: "实用新型专利",
          },
        },
        {
          dbid: "FgdsUTqAAAA",
          name: "一种隧道掘进爆破炮孔定位方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPZwYBE",
          number: "202210902128.1",
          appDate: "2022-07-29",
          authoredDate: "2022-09-30",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-11-02",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-11-01",
          history: [
            {
              dbid: "FghwtunAAAA",
              inteappId: "FgdsUTqAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-11-02T11:08:35.048Z",
            },
            {
              dbid: "FgdsXPvAAAA",
              inteappId: "FgdsUTqAAAA",
              statusId: "await",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:11:05.520Z",
            },
            {
              dbid: "FgdsUTrAAAU",
              inteappId: "FgdsUTqAAAA",
              statusId: "draft",
              userId: "Dc0rHt5hsAI",
              userName: "王建国",
              timestamp: "2022-11-01T16:10:53.484Z",
            },
          ],
          persons: [
            {
              dbid: "FgdsUTqAAAE",
              intelId: "FgdsUTqAAAA",
              userId: "Dc0rHt5hsAI",
              name: "王建国",
              personType: "js",
              order: 1,
              appNo: "20200096",
              deptName: "国土资源工程学院",
              contactsType: "fzr",
              contactsPhone: "13759587370",
              contactsEmail: "wangjg0831@163.com",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTqAAAI",
              intelId: "FgdsUTqAAAA",
              name: "陶家龙",
              personType: "yjs",
              order: 2,
              appNo: "20212201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTqAAAM",
              intelId: "FgdsUTqAAAA",
              name: "雷露刚",
              personType: "yjs",
              order: 3,
              appNo: "20212101095",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTqAAAQ",
              intelId: "FgdsUTqAAAA",
              userId: "Db2MP_CGQEg",
              name: "李祥龙",
              personType: "js",
              order: 4,
              appNo: "20100024",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTqAAAU",
              intelId: "FgdsUTqAAAA",
              name: "马军",
              personType: "yjs",
              order: 5,
              appNo: "20181101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTqAAAY",
              intelId: "FgdsUTqAAAA",
              name: "关思",
              personType: "yjs",
              order: 6,
              appNo: "20221201005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTrAAAA",
              intelId: "FgdsUTqAAAA",
              name: "张小华",
              personType: "yjs",
              order: 7,
              appNo: "20201201010",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTrAAAE",
              intelId: "FgdsUTqAAAA",
              name: "陶子豪",
              personType: "yjs",
              order: 8,
              appNo: "20201101017",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTrAAAI",
              intelId: "FgdsUTqAAAA",
              name: "左庭",
              personType: "yjs",
              order: 9,
              appNo: "20213101005",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
            {
              dbid: "FgdsUTrAAAM",
              intelId: "FgdsUTqAAAA",
              name: "赵泽虎",
              personType: "yjs",
              order: 10,
              appNo: "20221101025",
              deptName: "国土资源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPZwYBE",
            },
          ],
          department: {
            dbid: "DZb3OPZwYBE",
            name: "云南省财政厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FV7Z106AAAA",
          name: "一种减少计算重复的数据库查询关系建模方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZEapgUyQAQ",
          number: "202210896603.9",
          appDate: "2022-07-28",
          agencyId: "Ej7i_XYAAAA",
          source: "国家自然科学基金",
          statusId: "checked",
          submitDate: "2022-07-29",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-07-28",
          persons: [
            {
              dbid: "FY0QcWaAAAA",
              intelId: "FV7Z106AAAA",
              userId: "Db2MP-yGQGo",
              name: "游进国",
              personType: "js",
              order: 1,
              appNo: "20090008",
              deptName: "信息工程与自动化学院",
              contactsType: "fzr",
              contactsPhone: "15877958680",
              contactsEmail: "jgyou@126.com",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FY0QcWaAAAE",
              intelId: "FV7Z106AAAA",
              name: "何培蕾",
              personType: "yjs",
              order: 2,
              appNo: "20212104068",
              deptName: "信息工程与自动化学院",
              contactsType: "lxr",
              contactsPhone: "18402878475",
              contactsEmail: "2273816706@qq.com",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FY0QcWaAAAI",
              intelId: "FV7Z106AAAA",
              name: "徐静文",
              personType: "yjs",
              order: 3,
              appNo: "20202104080",
              deptName: "信息工程与自动化学院",
              contactsType: "ptr",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FY0QcWaAAAM",
              intelId: "FV7Z106AAAA",
              name: "柳大格",
              personType: "yjs",
              order: 4,
              appNo: "20212204223 ",
              deptName: "信息工程与自动化学院",
              contactsType: "ptr",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FY0QcWaAAAQ",
              intelId: "FV7Z106AAAA",
              name: "王宇轩",
              personType: "yjs",
              order: 5,
              appNo: "20212204156 ",
              deptName: "信息工程与自动化学院",
              contactsType: "ptr",
              deptId: "DZEapgUyQAQ",
            },
            {
              dbid: "FY0QcWbAAAA",
              intelId: "FV7Z106AAAA",
              userId: "Db2MP-yGQH0",
              name: "贾连印",
              personType: "js",
              order: 6,
              appNo: "20130011",
              deptName: "信息工程与自动化学院",
              contactsType: "ptr",
              deptId: "DZEapgUyQAQ",
            },
          ],
          department: {
            dbid: "DZEapgUyQAQ",
            name: "麒麟区政府",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FWOSBpDAAAA",
          name: "一种采用无扇叶风扇的计算机处理器散热装置",
          typeId: "Df_FW4NAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPawYBU",
          number: "202221909502.2",
          appDate: "2022-07-25",
          agencyId: "Ej7i_XYAAAA",
          statusId: "checked",
          submitDate: "2022-07-25",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-07-25",
          persons: [
            {
              dbid: "FYfcwpwAAAA",
              intelId: "FWOSBpDAAAA",
              userId: "Db2MP-zGQKU",
              name: "胡建杭",
              personType: "js",
              order: 1,
              appNo: "20030006",
              deptName: "冶金与能源工程学院",
              contactsType: "fzr",
              contactsPhone: "13529295096",
              contactsEmail: "hujh51@126.com",
              deptId: "DZb3OPawYBU",
            },
            {
              dbid: "FYfcwpwAAAE",
              intelId: "FWOSBpDAAAA",
              name: "马超维",
              personType: "yjs",
              order: 2,
              appNo: "20202202192",
              deptName: "冶金与能源工程学院",
              contactsType: "lxr",
              contactsPhone: "15825110936",
              contactsEmail: "1109492001@qq.com",
              deptId: "DZb3OPawYBU",
            },
            {
              dbid: "FYfcwpxAAAA",
              intelId: "FWOSBpDAAAA",
              name: "张凯歌",
              personType: "yjs",
              order: 3,
              appNo: "20202202191",
              deptName: "冶金与能源工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBU",
            },
          ],
          department: {
            dbid: "DZb3OPawYBU",
            name: "沿江乡政府",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FW4NAAAA",
            name: "实用新型专利",
          },
        },
        {
          dbid: "FV13HRiAAAA",
          name: "一种新型全向倾角传感器及其使用方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPawYA4",
          number: "202210878855.9",
          appDate: "2022-07-25",
          agencyId: "Ej7i_XYAAAA",
          source: "科研",
          statusId: "checked",
          submitDate: "2022-07-26",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-07-26",
          persons: [
            {
              dbid: "FYjwRqlAAAA",
              intelId: "FV13HRiAAAA",
              userId: "Db2MP_HGQBk",
              name: "胡方敏",
              personType: "js",
              order: 1,
              appNo: "12504007",
              deptName: "工程训练中心",
              contactsType: "fzr",
              contactsPhone: "13698797943",
              contactsEmail: "1011059800@qq.com",
              deptId: "DZb3OPawYA4",
            },
            {
              dbid: "FYjwRqlAAAE",
              intelId: "FV13HRiAAAA",
              name: "彭杰",
              personType: "yjs",
              order: 2,
              appNo: "20212245029",
              deptName: "民航与航空学院",
              contactsType: "ptr",
              deptId: "DZb3OPbwYAc",
            },
            {
              dbid: "FYjwRqlAAAI",
              intelId: "FV13HRiAAAA",
              userId: "Db2MP_HGQEo",
              name: "邓桂方",
              personType: "js",
              order: 3,
              appNo: "20090086",
              deptName: "民航与航空学院",
              contactsType: "ptr",
              deptId: "DZb3OPbwYAc",
            },
            {
              dbid: "FYjwRqlAAAM",
              intelId: "FV13HRiAAAA",
              userId: "Db2MP-yGQEE",
              name: "谢涛",
              personType: "js",
              order: 4,
              appNo: "12309079",
              deptName: "民航与航空学院",
              contactsType: "ptr",
              deptId: "DZb3OPbwYAc",
            },
          ],
          department: {
            dbid: "DZb3OPawYA4",
            name: "工程训练中心",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FWqK8eHAAAA",
          name: "一种园林花篱的促花修剪方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPbwYAY",
          number: "202210884103.3",
          appDate: "2022-07-25",
          agencyId: "Ej7i_XYAAAA",
          statusId: "checked",
          submitDate: "2022-07-27",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-07-27",
          persons: [
            {
              dbid: "FYp2UdfAAAA",
              intelId: "FWqK8eHAAAA",
              userId: "Db2MP-8GQIg",
              name: "郑伟",
              personType: "js",
              order: 1,
              appNo: "20090046",
              deptName: "建筑与城市规划学院",
              contactsType: "fzr",
              contactsPhone: "15025136865",
              contactsEmail: "57280234@qq.com",
              deptId: "DZb3OPbwYAY",
            },
            {
              dbid: "FYp2UdfAAAE",
              intelId: "FWqK8eHAAAA",
              name: "颜成敏",
              personType: "yjs",
              order: 2,
              appNo: "20202138042",
              deptName: "建筑与城市规划学院",
              contactsType: "lxr",
              contactsPhone: "18388077230",
              contactsEmail: "767244696@qq.com",
              deptId: "DZb3OPbwYAY",
            },
            {
              dbid: "FYp2UdfAAAI",
              intelId: "FWqK8eHAAAA",
              userId: "Db2MP-3GQAk",
              name: "徐晓丹",
              personType: "js",
              order: 3,
              appNo: "20090148",
              deptName: "建筑与城市规划学院",
              contactsType: "ptr",
              deptId: "DZb3OPbwYAY",
            },
          ],
          department: {
            dbid: "DZb3OPbwYAY",
            name: "大龙村",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FdqcsFFAAAA",
          name: "一种自生ZTA陶瓷增强铁基复合材料制备方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPawYBQ",
          number: "202210854642.2",
          appDate: "2022-07-20",
          authoredDate: "2022-09-27",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-09-28",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-09-27",
          history: [
            {
              dbid: "FdtR7NiAAAA",
              inteappId: "FdqcsFFAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-09-28T10:02:24.931Z",
            },
            {
              dbid: "Fdqc90aAAAA",
              inteappId: "FdqcsFFAAAA",
              statusId: "await",
              userId: "Db2MP_HGQJI",
              userName: "隋育栋",
              timestamp: "2022-09-27T20:51:47.547Z",
            },
            {
              dbid: "FdqcsFGAAAE",
              inteappId: "FdqcsFFAAAA",
              statusId: "draft",
              userId: "Db2MP_HGQJI",
              userName: "隋育栋",
              timestamp: "2022-09-27T20:50:34.887Z",
            },
          ],
          persons: [
            {
              dbid: "Fdqc7kmAAAA",
              intelId: "FdqcsFFAAAA",
              userId: "Db2MP_HGQJI",
              name: "隋育栋",
              personType: "js",
              order: 1,
              appNo: "20180070",
              deptName: "材料科学与工程学院",
              contactsType: "fzr",
              contactsPhone: "13619688136",
              contactsEmail: "suiyudong@126.com",
              deptId: "DZb3OPawYBQ",
            },
            {
              dbid: "Fdqc7kmAAAE",
              intelId: "FdqcsFFAAAA",
              userId: "Db2MP-VGQFY",
              name: "蒋业华",
              personType: "js",
              order: 2,
              appNo: "11303114",
              deptName: "科学技术院",
              contactsType: "fzr",
              contactsPhone: "13888661973",
              contactsEmail: "1742944769@qq.com",
              deptId: "Db2NIJQbgCU",
            },
            {
              dbid: "Fdqc7knAAAA",
              intelId: "FdqcsFFAAAA",
              userId: "EHCqk4oAAAA",
              name: "周谟金",
              personType: "js",
              order: 3,
              appNo: "20190070",
              deptName: "材料科学与工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBQ",
            },
            {
              dbid: "Fdqc7knAAAE",
              intelId: "FdqcsFFAAAA",
              userId: "Db2MP-VGQIA",
              name: "李祖来",
              personType: "js",
              order: 4,
              appNo: "20070003",
              deptName: "材料科学与工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBQ",
            },
          ],
          department: {
            dbid: "DZb3OPawYBQ",
            name: "莲华街道办事处",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "FWTU9eNAAAA",
          name: "一种形貌可控的铜铁矿型CuGaO2材料的制备方法",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPawYBQ",
          number: "202210806995.5",
          appDate: "2022-07-11",
          agencyId: "Ej7i_XYAAAA",
          source: "科研项目",
          statusId: "checked",
          submitDate: "2022-07-12",
          agentId: "Ej7kEJJAAAA",
          processStateId: "Dig1CShAAAA",
          managerId: "DpMDD6fAAAA",
          informationSource: "sq",
          outcomeStateId: "DkmP7U018Bg",
          processStateDate: "2022-07-12",
          persons: [
            {
              dbid: "FXbrGGMAAAA",
              intelId: "FWTU9eNAAAA",
              userId: "Db2MP_HGQGo",
              name: "赵宗彦",
              personType: "js",
              order: 1,
              appNo: "20110069",
              deptName: "材料科学与工程学院",
              contactsType: "fzr",
              contactsPhone: "13888045022",
              contactsEmail: "291575033@qq.com",
              deptId: "DZb3OPawYBQ",
            },
            {
              dbid: "FXbrGGMAAAE",
              intelId: "FWTU9eNAAAA",
              name: "李嘉琦",
              personType: "yjs",
              order: 2,
              appNo: "20202130014",
              deptName: "材料科学与工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPawYBQ",
            },
          ],
          department: {
            dbid: "DZb3OPawYBQ",
            name: "莲华街道办事处",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
        {
          dbid: "Fc2MomOAAAA",
          name: "基于混合MMC的BTB换流器及其控制系统V1.0",
          typeId: "Df_FwLXAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPZwYAI",
          number: "2022SR1166426",
          appDate: "2022-07-06",
          authoredDate: "2022-08-17",
          agencyId: "DmO7XtuAAAA",
          source: "科研",
          statusId: "checked",
          submitDate: "2022-09-19",
          processStateId: "DkmP7U018BY",
          managerId: "FDyv5m8AAAA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-09-17",
          history: [
            {
              dbid: "Fc-2BXVAAAA",
              inteappId: "Fc2MomOAAAA",
              statusId: "checked",
              userId: "FDyv5m8AAAA",
              userName: "李春筱",
              timestamp: "2022-09-19T09:37:58.166Z",
            },
            {
              dbid: "Fc-xPnvAAAA",
              inteappId: "Fc2MomOAAAA",
              statusId: "await",
              userId: "Db2MP-0GQJc",
              userName: "鲁思兆",
              timestamp: "2022-09-19T09:17:05.840Z",
            },
            {
              dbid: "Fc-sRBQAAAA",
              inteappId: "Fc2MomOAAAA",
              statusId: "returned",
              userId: "FDyv5m8AAAA",
              userName: "李春筱",
              timestamp: "2022-09-19T08:55:20.849Z",
            },
            {
              dbid: "Fc2sIokAAAA",
              inteappId: "Fc2MomOAAAA",
              statusId: "await",
              userId: "Db2MP-0GQJc",
              userName: "鲁思兆",
              timestamp: "2022-09-17T19:37:48.773Z",
            },
            {
              dbid: "Fc2MomPAAAM",
              inteappId: "Fc2MomOAAAA",
              statusId: "draft",
              userId: "Db2MP-0GQJc",
              userName: "鲁思兆",
              timestamp: "2022-09-17T17:20:11.088Z",
            },
          ],
          persons: [
            {
              dbid: "Fc2MomPAAAA",
              intelId: "Fc2MomOAAAA",
              userId: "Db2MP-0GQJc",
              name: "鲁思兆",
              personType: "js",
              order: 1,
              appNo: "20160023",
              deptName: "电力工程学院",
              contactsType: "lxr",
              contactsPhone: "13669790798",
              contactsEmail: "lusizhao6103@126.com",
              deptId: "DZb3OPZwYAI",
            },
            {
              dbid: "Fc2MomPAAAE",
              intelId: "Fc2MomOAAAA",
              name: "马晨",
              personType: "yjs",
              order: 2,
              appNo: "20202105008",
              deptName: "电力工程学院",
              contactsType: "fzr",
              contactsPhone: "18314026108",
              contactsEmail: "1578893898@qq.com",
              deptId: "DZb3OPZwYAI",
            },
          ],
          department: {
            dbid: "DZb3OPZwYAI",
            name: "曲靖市政府",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FwLXAAAA",
            name: "计算机软件著作权",
          },
        },
        {
          dbid: "Fcq-olzAAAA",
          name: " 一种地下塑料管网式种植灌溉水库 ",
          typeId: "Df_FSfJAAAA",
          affiliation: "gn",
          departmentId: "DZb3OPXwYAA",
          number: "202110754655.8",
          appDate: "2022-07-05",
          authoredDate: "2022-05-31",
          agencyId: "DmO7XtuAAAA",
          statusId: "checked",
          submitDate: "2022-09-19",
          processStateId: "DkmP7U018BY",
          managerId: "Db2MP-yGQHA",
          informationSource: "dj",
          outcomeStateId: "DkmP7U018Bk",
          processStateDate: "2022-09-15",
          history: [
            {
              dbid: "Fc_9YewAAAA",
              inteappId: "Fcq-olzAAAA",
              statusId: "checked",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-09-19T14:49:45.073Z",
            },
            {
              dbid: "Fc7UZ6QAAAA",
              inteappId: "Fcq-olzAAAA",
              statusId: "await",
              userId: "Db2MP-VGQDI",
              userName: "吴张永",
              timestamp: "2022-09-18T17:12:14.161Z",
            },
            {
              dbid: "FcvmEpYAAAA",
              inteappId: "Fcq-olzAAAA",
              statusId: "returned",
              userId: "Db2MP-yGQHA",
              userName: "李峰",
              timestamp: "2022-09-16T10:33:59.065Z",
              note: "请以证书为依据填写所有参与人信息（含学生和校外人员）！",
            },
            {
              dbid: "FcrX_KIAAAA",
              inteappId: "Fcq-olzAAAA",
              statusId: "await",
              userId: "Db2MP-VGQDI",
              userName: "吴张永",
              timestamp: "2022-09-15T14:53:57.705Z",
            },
            {
              dbid: "Fcq-ol0AAAI",
              inteappId: "Fcq-olzAAAA",
              statusId: "draft",
              userId: "Db2MP-VGQDI",
              userName: "吴张永",
              timestamp: "2022-09-15T13:03:11.669Z",
            },
          ],
          persons: [
            {
              dbid: "Fc7Tq6yAAAA",
              intelId: "Fcq-olzAAAA",
              userId: "Db2MP-VGQDI",
              name: "吴张永",
              personType: "js",
              order: 1,
              appNo: "11303048",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7Tq6zAAAA",
              intelId: "Fcq-olzAAAA",
              userId: "Db2MP-VGQIs",
              name: "莫子勇",
              personType: "js",
              order: 2,
              appNo: "20120148",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7Tq6zAAAE",
              intelId: "Fcq-olzAAAA",
              name: "蒋佳骏",
              personType: "yjs",
              order: 3,
              appNo: "20203103003",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7Tq6zAAAI",
              intelId: "Fcq-olzAAAA",
              name: "朱启晨",
              personType: "yjs",
              order: 4,
              appNo: "20191103001",
              deptName: "机电工程学院",
              contactsType: "ptr",
              deptId: "DZb3OPXwYAA",
            },
            {
              dbid: "Fc7Tq6zAAAM",
              intelId: "Fcq-olzAAAA",
              name: "卞光明",
              personType: "xw",
              order: 5,
            },
            {
              dbid: "Fc7Tq6zAAAQ",
              intelId: "Fcq-olzAAAA",
              name: "马自刚",
              personType: "xw",
              order: 6,
            },
            {
              dbid: "Fc7Tq6zAAAU",
              intelId: "Fcq-olzAAAA",
              name: "代龙",
              personType: "xw",
              order: 7,
            },
            {
              dbid: "Fc7Tq6zAAAY",
              intelId: "Fcq-olzAAAA",
              name: "曹鹏",
              personType: "xw",
              order: 8,
            },
            {
              dbid: "Fc7Tq6zAAAc",
              intelId: "Fcq-olzAAAA",
              name: "曹红",
              personType: "xw",
              order: 9,
            },
          ],
          department: {
            dbid: "DZb3OPXwYAA",
            name: "云南省教育厅",
          },
          status: {
            dbid: "DgeUB4Xh0AE",
            name: "已审核",
            identifier: "checked",
            rank: 50,
            color: "blue",
          },
          actions: [
            {
              dbid: "DijG18IBcAM",
              from: "checked",
              to: "await",
              action: "revoke",
              name: "撤销审核",
              note: "撤销审核，状态改回待审核",
            },
          ],
          type: {
            dbid: "Df_FSfJAAAA",
            name: "发明专利",
          },
        },
      ],
    };
  },
  methods: {
    showDetail(patent) {
      // localStorage只能存储字符串，所以需要将对象转换为json字符串
      localStorage.setItem("patent_detail", JSON.stringify(patent));
      this.$router.push({ name: "detail", params: { id: patent.dbid } });
      // this.$router.push(`/detail/${patentId}`);
    },
  },
  components: {
    IonPage,
    IonHeader,
    IonToolbar,
    IonButtons,
    IonBackButton,
    IonTitle,
    IonContent,
    IonList,
    IonItem,
    IonSearchbar,
    IonGrid,
    IonRow,
    IonCol,
  },
};
</script>
    
<style scoped>
.grid-scroll {
  flex-wrap: nowrap;
  overflow-x: scroll !important;
}
.row-head {
  flex-wrap: nowrap;
  /* background-color: #fff; */
}
.row-scroll {
  flex-wrap: nowrap;
  /* background-color: #fff; */
}

ion-col {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
tr:nth-child(even) {
  background-color: #f2f2f2;
}
</style>